my_project:
  outputs:
    dev:
      type: postgres
      host: db
      user: "{{ env_var('POSTGRES_USER', 'user') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB', 'weather_data') }}"
      schema: weather_data
      threads: 4
  target: dev
