version: 2

sources:
  - name: weather_data
    description: "Source table for weather data"
    tables:
      - name: weather_data
        description: "Table containing weather data"
        columns:
          - name: id
          - name: city
          - name: temperature
          - name: weather_description
          - name: wind_speed
          - name: time
          - name: inserted_at
          - name: utc_offset