name: QA

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Docker (for testcontainers)
        uses: docker/setup-buildx-action@v3

      - name: Install QA deps
        run: |
          python -m pip install -U pip
          pip install -r qa/requirements.txt

      - name: Run QA tests
        working-directory: qa
        run: pytest -c pytest.ini
